### PR TITLE
Relax dependency version constraints

### PR DESCRIPTION
**Pull request by yossigo**
No special features are used, so practically any version should be good.

### CODE REVIEW

**Comment by rafie** [comment]
We fixed the redis-py version because newer version were breaking RAMP/RLTest. It might be related to redis-py-cluster. I'm trying to reproduce that.
Are you trying to use RAMP with redis-py 3.x?

**Comment by yossigo** [comment]
@rafie mainly trying to resolve Python conflicts which result from such an old version being used. Checked that with @swilly22 who thought it wouldn't matter.
What problems did you encounter? Perhaps I can try to help resolve them with recent versions of redis-py.

**Comment by rafie** [comment]
@yossigo I cannot recall the exact issue, so I'm doing a screening test with several modules.

**Comment by rafie** [comment]
@yossigo Ok, I checked with RedisGears, RediSearch, RedisTimeSeries, and RedisGraph, all work well.
Would you like to try removing the semantic_version constraint as well?

**Comment by yossigo** [comment]
@rafie added a commit for `semantic_version` as well, doesn't seem like it should break.

**Pull request merged**
